### ISSUE TITLE
Problem installing with opencv 3.0

### ISSUE THREAD

**Issue by MuhammadUsman90** [uzh-rpg/rpg_svo#128]
Did someone tried to compile with opencv 3.0 since i am having numurous errors like CV_FILLED was not declared in this scope..

**Comment by VishnuDuttSharma** [comment]
I also got errors while compiling with OpenCV 3.0 . There are some functions which work only woth OpenCV2.x.x, so I reinstalled OpenCV with version 2.4.11 and it worked.
